Repository dosenk/rsclone, pull requests merged in 2021-02, with the labels that each got.

#127 fix: fix logout bug
  src/Components/Game/index.Game.ts
  src/Observer/index.Observer.ts
  src/SocketIoClient/index.SocketIoClient.ts
  src/pages/login.ts
Labels: bug

#126 Timer
  src/Components/Game/index.Game.ts
  src/Components/Timer/imdex.Timer.ts
  src/Components/Timer/index.Timer.scss
  src/Constants/classNames.ts
  src/SocketIoClient/index.SocketIoClient.ts
  src/styles/index.scss
Labels: enhancement

#129 feat: add touch listener
  src/Components/Board/index.Board.ts
Labels: enhancement

#130 fix: bag with board
  src/Components/Board/board.scss
  src/Components/Board/index.Board.ts
Labels: bug

#128 Styles
  package.json
  src/Components/Board/board.scss
  src/Components/Board/index.Board.ts
  src/Components/Game/GameEvents/GuessWord/index.GameGuessWord.scss
  src/Components/Game/game.scss
  src/Components/Game/index.Game.ts
  src/Components/PageLayout/constants.PageLayout.ts
  src/Components/Panel/index.Panel.ts
  src/Components/Panel/panel.scss
  src/Components/Timer/imdex.Timer.ts
  src/Components/Timer/index.Timer.scss
  src/Components/Users/index.Users.ts
  src/Components/Users/users.scss
  src/Constants/classNames.ts
  src/Constants/index.Constants.ts
  src/LangDictionaries/by.ts
  src/LangDictionaries/en.ts
  src/LangDictionaries/ru.ts
  src/SocketIoClient/index.SocketIoClient.ts
  src/SocketIoClient/style.chat.scss
  src/Utils/index.Utils.ts
  src/pages/login.ts
  src/styles/index.scss
  src/styles/main.scss
Labels: enhancement

#132 feat: added responsive layout
  src/Components/Board/board.scss
  src/Components/Board/index.Board.ts
  src/Components/Game/GameEvents/GuessWord/index.GameGuessWord.scss
  src/Components/Game/game.scss
  src/Components/Game/index.Game.ts
  src/Components/MainPage/mainPage.scss
  src/Components/PageLayout/constants.PageLayout.ts
  src/Components/PageLayout/styles.PageLayout.scss
  src/Components/Timer/index.Timer.scss
  src/Components/Users/index.Users.ts
  src/Components/Users/users.scss
  src/Constants/classNames.ts
  src/SocketIoClient/index.SocketIoClient.ts
  src/SocketIoClient/style.chat.scss
  src/styles/constants.scss
  src/styles/main.scss
Labels: enhancement

#134 fix: unable to change language from login page
  src/pages/login.ts
Labels: bug

#135 Users bug
  src/Components/Board/board.scss
  src/Components/Board/index.Board.ts
  src/Components/Game/GameEvents/GuessWord/index.GameGuessWord.scss
  src/Components/Users/Interfaces/IGuessers.ts
  src/Components/Users/Interfaces/IPainter.ts
  src/Components/Users/index.Users.ts
  src/Observer/Interfaces/IState.ts
  src/assets/ico/favicon.ico
  webpack.config.js
Labels: bug

#137 fix: bug with cursor
  src/Components/Board/index.Board.ts
Labels: bug

#138 feat: add error block
  src/Components/Login/constants.ts
  src/Components/Login/index.Login.ts
  src/LangDictionaries/by.ts
  src/LangDictionaries/en.ts
  src/LangDictionaries/ru.ts
  src/pages/styles/userEntrance.scss
Labels: enhancement

#139 feat: update readmy, delete test script
  README.md
  package.json
Labels: documentation
