Repository dosenk/rsclone, pull requests merged in 2021-01, with the labels that each got.

#21 refactor: add createElement() to Utils
  src/Utils/index.Utils.ts
Labels: Refactor

#23 Multi language support
  src/Components/App/index.App.ts
  src/Constants/index.Constants.ts
  src/LangDictionaries/by.ts
  src/LangDictionaries/en.ts
  src/LangDictionaries/index.LangDictionaries.ts
  src/LangDictionaries/ru.ts
  src/Observer/ActionCreator.ts
  src/Observer/Interfaces/IAction.ts
  src/Observer/Interfaces/IState.ts
  src/Observer/Interfaces/ISubscriber.ts
  src/Observer/actionTypes.ts
  src/Observer/index.Observer.ts
  src/Observer/reducer.ts
Labels: Refactor

#28 refactor: add .prettierrc
  .eslintrc.js
  .prettierrc
  package.json
  src/Constants/classNames.ts
  src/Utils/index.Utils.ts
Labels: Refactor

#34 Actions for setting name, role, color, thickness, and data of drawing
  src/Observer/ActionCreator.ts
  src/Observer/Interfaces/IDraw.ts
  src/Observer/Interfaces/IState.ts
  src/Observer/actionTypes.ts
  src/Observer/index.Observer.ts
  src/Observer/reducer.ts
Labels: Refactor

#42 Routing
  src/Components/App/index.App.ts
  src/Constants/index.Constants.ts
  src/Constants/pages.ts
  src/Constants/routes.ts
  src/Observer/ActionCreator.ts
  src/Router/index.Router.ts
  src/Utils/index.Utils.ts
  src/index.html
  src/pages/game.ts
  src/pages/index.pages.ts
  src/pages/landing.ts
  src/pages/login.ts
  src/pages/registration.ts
  src/pages/settings.ts
  src/pages/statistics.ts
  src/styles/main.scss
  webpack.config.js
Labels: enhancement

#52 feat: complited preloader class
  src/Components/Preloader/index.Preloader.ts
  src/Components/Preloader/preloader.scss
  src/assets/images/giphy.gif
  src/styles/index.scss
Labels: enhancement

#54 fix: duplicate Observer subscribers
  src/Components/Board/index.Board.ts
  src/Components/Users/index.Users.ts
  src/SocketIoClient/index.SocketIoClient.ts
  src/pages/game.ts
Labels: bug

#57 bag: fix bag with panel
  src/Components/Panel/panel.scss
Labels: bug

#58 Use singletons
  src/Components/Board/index.Board.ts
  src/Components/Users/index.Users.ts
  src/Observer/index.Observer.ts
  src/Router/index.Router.ts
  src/Router/index.d.ts
  src/SocketIoClient/index.SocketIoClient.ts
  src/pages/game.ts
Labels: bug

#69 refactor: add Router.addRoutes()
  src/Components/App/index.App.ts
  src/Constants/index.Constants.ts
  src/Router/index.Router.ts
  src/Router/index.d.ts
Labels: Refactor

#67 Login reg page switcher
  src/Components/Login/constants.ts
  src/Components/Login/index.Login.ts
  src/Components/Login/login.scss
  src/Components/Registration/constants.ts
  src/Components/Registration/index.Registration.ts
  src/Components/Registration/registration.scss
  src/Constants/classNames.ts
  src/LangDictionaries/by.ts
  src/LangDictionaries/en.ts
  src/LangDictionaries/ru.ts
  src/Observer/Interfaces/IState.ts
  src/Utils/index.Utils.ts
  src/pages/login.ts
  src/pages/registration.ts
  src/styles/constants.scss
  src/styles/index.scss
  src/styles/main.scss
  src/styles/shared.scss
Labels: enhancement

#73 Word select
  src/Components/Game/index.Game.ts
  src/Components/Login/login.scss
  src/Components/Registration/registration.scss
  src/Components/SelectWord/constants.ts
  src/Components/SelectWord/index.SelectWord.scss
  src/Components/SelectWord/index.SelectWord.ts
  src/LangDictionaries/by.ts
  src/LangDictionaries/en.ts
  src/LangDictionaries/ru.ts
  src/Observer/ActionCreator.ts
  src/Observer/Interfaces/IState.ts
  src/Observer/actionTypes.ts
  src/Observer/index.Observer.ts
  src/Observer/reducer.ts
  src/SocketIoClient/constants.ts
  src/SocketIoClient/index.SocketIoClient.ts
  src/pages/game.ts
  src/styles/index.scss
  src/styles/shared.scss
Labels: enhancement

#78 Game end popup
  src/Components/GameEnd/constants.GameEnd.ts
  src/Components/GameEnd/index.GameEnd.scss
  src/Components/GameEnd/index.GameEnd.ts
  src/Components/Modal/constants.Modal.ts
  src/Components/Modal/index.Modal.ts
  src/Components/Modal/styles.Modal.scss
  src/LangDictionaries/by.ts
  src/LangDictionaries/en.ts
  src/LangDictionaries/ru.ts
  src/styles/index.scss
Labels: enhancement

#83 Game Statuses
  src/Components/Game/index.Game.ts
  src/Components/Game/statuses.ts
  src/Components/GameEnd/index.GameEnd.ts
  src/Components/Preloader/index.Preloader.ts
  src/Components/Preloader/preloader.scss
  src/LangDictionaries/by.ts
  src/LangDictionaries/en.ts
  src/LangDictionaries/ru.ts
  src/Observer/ActionCreator.ts
  src/Observer/Interfaces/IGameEndInfo.ts
  src/Observer/Interfaces/IState.ts
  src/Observer/actionTypes.ts
  src/Observer/index.Observer.ts
  src/Observer/reducer.ts
  src/SocketIoClient/index.SocketIoClient.ts
  src/styles/shared.scss
Labels: Refactor

#84 fix: answer case sensitivity
  src/SocketIoClient/constants.ts
  src/SocketIoClient/index.SocketIoClient.ts
Labels: bug

#92 Header & Footer & language changing
  src/Components/App/index.App.ts
  src/Components/PageLayout/constants.PageLayout.ts
  src/Components/PageLayout/index.PageLayout.ts
  src/Components/PageLayout/styles.PageLayout.scss
  src/Constants/classNames.ts
  src/LangDictionaries/by.ts
  src/LangDictionaries/en.ts
  src/LangDictionaries/ru.ts
  src/Router/index.Router.ts
  src/Utils/index.Utils.ts
  src/assets/images/blr.svg
  src/assets/images/gbr.svg
  src/assets/images/rs_logo.svg
  src/assets/images/rus.svg
  src/pages/game.ts
  src/pages/login.ts
  src/pages/settings.ts
  src/pages/statistics.ts
  src/styles/constants.scss
  src/styles/index.scss
  src/styles/main.scss
  src/styles/shared.scss
Labels: enhancement

#97 Add langBtn to login & registration
  src/Components/Login/index.Login.ts
  src/Components/PageLayout/constants.PageLayout.ts
  src/Components/PageLayout/index.PageLayout.ts
  src/Components/PageLayout/styles.PageLayout.scss
  src/Components/Registration/constants.ts
  src/Components/Registration/index.Registration.ts
  src/Components/Registration/registration.scss
  src/Constants/classNames.ts
  src/LangDictionaries/by.ts
  src/LangDictionaries/en.ts
  src/LangDictionaries/ru.ts
  src/Utils/index.Utils.ts
  src/styles/main.scss
Labels: enhancement

#99 Game rerender bug
  src/Components/Game/index.Game.ts
  src/Components/GameEnd/index.GameEnd.ts
  src/Components/PageLayout/index.PageLayout.ts
  src/pages/game.ts
Labels: bug

#98 Game links
  src/Components/PageLayout/index.PageLayout.ts
  src/Components/PageLayout/styles.PageLayout.scss
  src/LangDictionaries/by.ts
  src/LangDictionaries/en.ts
  src/LangDictionaries/ru.ts
  src/Router/index.Router.ts
Labels: enhancement

#104 Main page with statistics
  src/Components/MainPage/index.MainPage.ts
  src/Components/MainPage/mainPage.scss
  src/LangDictionaries/by.ts
  src/LangDictionaries/en.ts
  src/LangDictionaries/ru.ts
  src/assets/images/avatar.jpg
  src/assets/images/people.png
  src/pages/statistics.ts
  src/styles/index.scss
  src/styles/main.scss
Labels: enhancement

#107 Word select painter
  src/Components/Game/GameEvents/GuessWord/index.GameGuessWord.scss
  src/Components/Game/GameEvents/GuessWord/index.GameGuessWord.ts
  src/Components/Game/GameEvents/Popaps/index.GamePopaps.scss
  src/Components/Game/GameEvents/Popaps/index.GamePopaps.ts
  src/Components/Game/GameEvents/constants.GameEvents.ts
  src/Components/Game/index.Game.ts
  src/Constants/classNames.ts
  src/styles/index.scss
Labels: enhancement

#108 Game start screen
  src/Components/Game/GameEvents/Popaps/index.GamePopaps.ts
  src/Components/Game/index.Game.ts
  src/Components/Login/index.Login.ts
  src/Components/PageLayout/styles.PageLayout.scss
  src/Constants/classNames.ts
  src/LangDictionaries/by.ts
  src/LangDictionaries/en.ts
  src/LangDictionaries/ru.ts
  src/Observer/ActionCreator.ts
Labels: enhancement

#113 Fix rerender canvas
  src/Components/Board/index.Board.ts
  src/Components/Game/index.Game.ts
  src/Components/Login/index.Login.ts
  src/Components/Panel/index.Panel.ts
  src/Components/Registration/index.Registration.ts
  src/styles/main.scss
Labels: bug

#118 Game translation
  src/Components/Login/constants.ts
  src/Components/Login/index.Login.ts
  src/Components/Login/login.scss
  src/Components/Registration/constants.ts
  src/Components/Registration/index.Registration.ts
  src/Components/Users/constants.ts
  src/Components/Users/index.Users.ts
  src/LangDictionaries/by.ts
  src/LangDictionaries/en.ts
  src/LangDictionaries/ru.ts
  src/pages/landing.ts
  src/pages/styles/landing.scss
  src/pages/styles/userEntrance.scss
  src/styles/index.scss
Labels: enhancement

#119 refactor: add gender selection and fetcher class
  src/Components/Game/index.Game.ts
  src/Components/Login/index.Login.ts
  src/Components/MainPage/index.MainPage.ts
  src/Components/Registration/constants.ts
  src/Components/Registration/index.Registration.ts
  src/Fetcher/index.Fetcher.ts
  src/LangDictionaries/by.ts
  src/LangDictionaries/en.ts
  src/LangDictionaries/ru.ts
  src/pages/styles/userEntrance.scss
Labels: Refactor

#121 feat: complited class rating & add avatar for man and woman
  src/Components/MainPage/index.MainPage.ts
  src/Components/MainPage/mainPage.scss
  src/Components/Rating/constants.ts
  src/Components/Rating/index.Rating.ts
  src/Components/Rating/rating.scss
  src/Observer/Interfaces/IRatingUser.ts
  src/assets/images/avatar.jpg
  src/assets/images/man.png
  src/assets/images/woman.png
  src/styles/index.scss
Labels: enhancement
